### PR TITLE
Add sterricson's busybox 1.26.2 (incl. handpicked applets)

### PR DESCRIPTION
**Pull request by alamo18**
I'm sorry can you take the trouble to resign the entire repo when you get to the next release?

### CODE REVIEW

**Comment by alamo18** [comment]
sorry for the 3 commits, but 2 of them is to sync the repo(i forgot)

**Comment by Tkkg1994** [comment]
Why you want to copy those files instead of running the official installer?

**Comment by alamo18** [comment]
basically, i forgot to sync repo, and thus worked on my local repo that was 15 commits back. I realised that, and pulled from the upstream repo and merged my commits with yours, but something went kablooey and i had to manually merge those and ended up committing once more

**Comment by Tkkg1994** [comment]
Can you please make a new pull request with only one commit?

**Comment by alamo18** [comment]
yeap ok XD

**Pull request closed without merging**
